---
- hosts: kubernetes-master-nodes
  gather_facts: no
  become: yes
  roles:
    - { role: roles/common } #Contains etc/hosts modifying and package installation
    - { role: roles/kubemaster }
- hosts: kubernetes-worker-nodes
  gather_facts: no
  become: yes
  roles:
    - { role: roles/common } #Contains etc/hosts modifying and package installation
    - { role: roles/kubeworker }
