---
# tasks file for kubeworker
- name: Copying token to worker nodes
  copy:
    src: "{{ token_file }}"
    dest: join_token
- name: Join node to cluster
  shell: |
    kubeadm join {{hostvars[item]['ansible_host']}} --token {{token_file}}
  with_items: "{{ kubernetes-master-nodes }}"
